(function(g){var window=this;'use strict';var wg0=function(D,O){if(!Number.isFinite(D))return String(D);D=String(D);var h=D.indexOf(".");h===-1&&(h=D.length);var V=D[0]==="-"?"-":"";V&&(D=D.substring(1));return V+(0,g.Rde)("0",Math.max(0,O-h))+D},s5R=function(){return{X:"svg",
B:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},N:[{X:"path",B:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.64-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.63 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2z"}}]}},Wp_=function(){return{X:"svg",
B:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},N:[{X:"path",B:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.63-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.64 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2zm-2 1H8v-6c0-2.48 1.51-4.5 4-4.5s4 2.02 4 4.5v6z"}}]}},d48=function(D){typeof D==="number"?(this.date=T7e(D,0,1),fC(this,1)):g.pT(D)?(this.date=T7e(D.getFullYear(),D.getMonth(),D.getDate()),fC(this,D.getDate())):(this.date=new Date(g.xw()),D=this.date.getDate(),
this.date.setHours(0),this.date.setMinutes(0),this.date.setSeconds(0),this.date.setMilliseconds(0),fC(this,D))},T7e=function(D,O,h){O=new Date(D,O,h);
D>=0&&D<100&&O.setFullYear(O.getFullYear()-1900);return O},fC=function(D,O){D.getDate()!=O&&D.date.setUTCHours(D.date.getUTCHours()+(D.getDate()<O?1:-1))},KC=function(D,O){g.DK.call(this,D,{X:"div",
Y:"ytp-reminder-menu",B:{role:"menu",tabindex:"-1"},N:[{X:"div",Y:"ytp-reminder-menu-contents",N:[{X:"div",Y:"ytp-reminder-menu-items"}]}]},100,!0);this.D=O;this.j=[];this.menuPopupRenderer=void 0;this.items=this.z2("ytp-reminder-menu-items");this.hide()},z_R=function(D){return(D.menuPopupRenderer&&D.menuPopupRenderer.items||[]).reduce(function(O,h){h&&h.menuServiceItemRenderer&&O.push(h.menuServiceItemRenderer);
return O},[])},Er=function(D){g.N.call(this,{X:"div",
N:[{X:"button",Z8:["ytp-offline-slate-button","ytp-button"],N:[{X:"div",Y:"ytp-offline-slate-button-icon",W3:"{{icon}}"},{X:"div",Y:"ytp-offline-slate-button-text",W3:"{{text}}"}]}]});this.C=D;this.upcomingEventReminderButtonRenderer=this.toggleButtonRenderer=null;this.K=void 0;this.W=this.D=null;(this.J=this.z2("ytp-offline-slate-button"))&&this.G(this.J,"click",this.L);this.hide()},Fp8=function(D,O,h){!D.toggleButtonRenderer&&O&&O.toggleButtonRenderer?D.toggleButtonRenderer=O.toggleButtonRenderer:
O&&O.toggleButtonRenderer||(D.toggleButtonRenderer=null);
!D.upcomingEventReminderButtonRenderer&&h&&g.y(h,n0_)?D.upcomingEventReminderButtonRenderer=g.y(h,n0_):h&&g.y(h,n0_)||(D.upcomingEventReminderButtonRenderer=null);js(D)},js=function(D){if(D.toggleButtonRenderer){var O=D.toggleButtonRenderer;
if(O.isToggled){var h=O.toggledText?g.ag(O.toggledText):"";D.update({text:h,icon:yqm(O.toggledIcon)})}else h=O.defaultText?g.ag(O.defaultText):"",D.update({text:h,icon:yqm(O.defaultIcon)});D.show()}else D.upcomingEventReminderButtonRenderer?(O=iHx(D))?(h=O.text?g.ag(O.text):"",D.update({text:h,icon:yqm(O.icon)}),D.show()):D.hide():D.hide()},pgL=function(D,O,h){D.W||(D.W=new g.Yb(D.C.V().UU));
var V={context:g.AN(D.W.config_||g.KL())};g.QK()&&(V.context.clientScreenNonce=g.QK());V.params=h;g.J8(D.W,O,V,{timeout:5E3,onSuccess:function(){D.upcomingEventReminderButtonRenderer&&D.K&&(D.upcomingEventReminderButtonRenderer.currentState=D.K,D.K=void 0)},
onError:function(){rqJ(D)},
onTimeout:function(){rqJ(D)}})},rqJ=function(D){D.toggleButtonRenderer?(D.toggleButtonRenderer.isToggled=!D.toggleButtonRenderer.isToggled,js(D)):D.upcomingEventReminderButtonRenderer&&(D.K=void 0,js(D))},yqm=function(D){if(!D)return null;
switch(D.iconType){case "NOTIFICATIONS":return s5R();case "NOTIFICATIONS_NONE":return Wp_();case "NOTIFICATIONS_ACTIVE":return g.tA();default:return null}},iHx=function(D){if(!D.upcomingEventReminderButtonRenderer)return null;
var O=D.K||D.upcomingEventReminderButtonRenderer.currentState;D=g.P(D.upcomingEventReminderButtonRenderer.states||[]);for(var h=D.next();!h.done;h=D.next())if((h=g.y(h.value,N7v))&&h.state===O&&h.button&&g.y(h.button,g.zY))return g.y(h.button,g.zY);return null},o0x=function(D){g.N.call(this,{X:"div",
Y:"ytp-offline-slate",N:[{X:"div",Y:"ytp-offline-slate-background"},{X:"div",Y:"ytp-offline-slate-bar",N:[{X:"span",Y:"ytp-offline-slate-icon",N:[{X:"svg",B:{fill:"#fff",height:"100%",viewBox:"0 0 24 24",width:"100%"},N:[{X:"path",B:{d:"M16.94 6.91l-1.41 1.45c.9.94 1.46 2.22 1.46 3.64s-.56 2.71-1.46 3.64l1.41 1.45c1.27-1.31 2.05-3.11 2.05-5.09s-.78-3.79-2.05-5.09zM19.77 4l-1.41 1.45C19.98 7.13 21 9.44 21 12.01c0 2.57-1.01 4.88-2.64 6.54l1.4 1.45c2.01-2.04 3.24-4.87 3.24-7.99 0-3.13-1.23-5.96-3.23-8.01zM7.06 6.91c-1.27 1.3-2.05 3.1-2.05 5.09s.78 3.79 2.05 5.09l1.41-1.45c-.9-.94-1.46-2.22-1.46-3.64s.56-2.71 1.46-3.64L7.06 6.91zM5.64 5.45L4.24 4C2.23 6.04 1 8.87 1 11.99c0 3.13 1.23 5.96 3.23 8.01l1.41-1.45C4.02 16.87 3 14.56 3 11.99s1.01-4.88 2.64-6.54z"}},
{X:"circle",B:{cx:"12",cy:"12",r:"3"}}]}]},{X:"span",Y:"ytp-offline-slate-messages",N:[{X:"div",Y:"ytp-offline-slate-main-text",B:{"aria-label":"{{label}}"},W3:"{{mainText}}"},{X:"div",Y:"ytp-offline-slate-subtitle-text",W3:"{{subtitleText}}"}]},{X:"span",Y:"ytp-offline-slate-buttons"}]},{X:"button",Z8:["ytp-offline-slate-close-button","ytp-button"],N:[g.jg()]},{X:"button",Z8:["ytp-offline-slate-open-button","ytp-button"],N:[g.E1()]}]});var O=this;this.api=D;this.D=this.K=null;this.background=this.z2("ytp-offline-slate-background");
this.j=this.z2("ytp-offline-slate-bar");this.J=new g.VQ(function(){g.JX(O.j,"ytp-offline-slate-bar-fade")},15E3);
this.L=!1;this.W=new g.VQ(function(){g.JX(O.element,"ytp-offline-slate-collapsed")},15E3);
g.F(this,this.W);g.F(this,this.J);this.countdownTimer=new g.VQ(this.US,1E3,this);this.G(D,"presentingplayerstatechange",this.t3);this.G(D,"livestatedata",this.x7);this.G(this.z2("ytp-offline-slate-close-button"),"click",function(){g.JX(O.element,"ytp-offline-slate-collapsed")});
this.G(this.z2("ytp-offline-slate-open-button"),"click",function(){g.uY(O.element,"ytp-offline-slate-collapsed")});
this.hide();D=this.getVideoData();D.getPlayerResponse()&&(D=D.getPlayerResponse().playabilityStatus)&&this.x7(D);D=this.api.getPresentingPlayerType()===8&&!this.getVideoData().Ig;var h=this.api.getPresentingPlayerType()===8;g.my(this.element,"ytp-offline-slate-premiere-trailer",D);g.my(this.element,"ytp-offline-slate-hide-background",h)},ZHe=function(D,O,h){if(O){var V=O.subtitleText!=null?g.ag(O.subtitleText):"";
h=h?h:O.mainText!=null?g.ag(O.mainText):"";var k,C,M,c;O=(c=(k=O.mainText)==null?void 0:(C=k.accessibility)==null?void 0:(M=C.accessibilityData)==null?void 0:M.label)!=null?c:h;D.update({mainText:h,subtitleText:V,label:O});g.my(D.element,"ytp-offline-slate-single-text-line",!V);g.my(D.j,"ytp-offline-slate-bar-hidden",!h&&!V)}},Ur=function(D,O){var h=(0,g.sk)();
this.module="heartbeat";this.trigger=D;this.D=O;this.j=h},I4v=function(D){g.dX.call(this,D);
var O=this;this.L=!1;this.T=0;this.J=!1;this.K=new g.VQ(function(){Xg8(O)},0);
this.D=this.heartbeatParams=null;this.W=!1;this.Z=new g.wj(1E3,6E4,1);this.sequenceNumber=0;this.offlineSlate=null;this.Ew=new g.Yb(void 0);this.attestationResponse=Promise.resolve(void 0);this.U=Promise.resolve(void 0);this.utcOffsetMinutes=-(new d48).getTimezoneOffset();this.j=new g.Fh(this);g.F(this,this.K);g.F(this,this.j);B7e(this);l4c(this);this.j.G(D,"heartbeatparams",this.FE);this.j.G(D,"presentingplayerstatechange",this.sO);this.j.G(D,"videoplayerreset",this.gM);this.j.G(D,g.Y8("heartbeat"),
this.onCueRangeEnter);this.W&&this.D&&x4c(this,void 0,this.D);var h=new g.cw(1E3,0x7ffffffffffff,{priority:1,namespace:"heartbeat"}),V=new g.cw(0x8000000000000,0x8000000000000,{id:"stream_end",priority:1,namespace:"heartbeat"});D.B2([h,V]);$49(this)},$49=function(D){var O=D.getVideoData();
!O.S("use_rta_for_player")&&O.jy&&(O=O.botguardData)&&g.Td(O,D.player.V())},D8C=function(D){var O,h;
return g.Q(function(V){if(V.D==1)return g.t(V,g.jBd(),2);if(!V.K)return D.sequenceNumber>=3?V.return({error:"ATTESTATION_ERROR_VM_INTERNAL_ERROR"}):V.return(void 0);O=D.getVideoData();h={};return V.return(g.Enw((h.cpn=O.clientPlaybackNonce,h.encryptedVideoId=O.videoId||"",h),1500))})},B7e=function(D){var O=D.getVideoData();
if(O.jy)if(O.S("use_rta_for_player"))D.attestationResponse=D8C(D);else if(O=new g.ghq(O),g.Qo.isInitialized()||D.sequenceNumber>=3){var h=Promise,V=h.resolve,k=null;if(O.videoData.ZP){var C=g.RYe(O);if(C){k={};var M={};C=C.split("&");C=g.P(C);for(var c=C.next();!c.done;c=C.next())c=c.value.split("="),c.length===2&&(M[c[0]]=c[1]);M.r1a&&(k.webResponse=M.r1a);M.r1c&&(k.error=OwU[Number(M.r1c)]);k.challenge=O.videoData.ZP}}D.attestationResponse=V.call(h,k||void 0)}},htx=function(D){var O=D.getVideoData();
if(!g.g$(D.getVideoData())||O.JM)return!1;if(O.J){D=O.J.flavor==="playready"&&O.S("html5_innertube_heartbeats_for_playready");var h=O.J.flavor==="widevine"&&O.S("html5_innertube_heartbeats_for_widevine");O=g.dH(O.J)&&O.S("html5_innertube_heartbeats_for_fairplay");return!(D||h||O)}return!0},VhR=function(D){if(htx(D))return!!D.heartbeatParams;
var O=D.getVideoData();return!g.g$(D.getVideoData())||O.Ds||O.WY?!!O.heartbeatToken:!1},Ao=function(D,O){if(!D.K.isActive()&&D.L){var h=D.getVideoData();
if(VhR(D)||h.isLivePlayback){if(O===void 0)if(D.J)if(D.W)O=7500;else{var V;O=((V=D.heartbeatParams)==null?0:V.interval)?D.heartbeatParams.interval*1E3:D.getVideoData().pL||6E4}else O=1E3;D.K.start(O)}}},bwL=function(D,O,h){O.IA&&(h=g.lF(h,{internalipoverride:O.IA}));
var V={cpn:O.clientPlaybackNonce};O.contextParams&&(V.context_params=O.contextParams);O.Uw&&(V.kpt=O.Uw);h=g.lF(h,V);g.QR(h,{format:"RAW",method:"GET",timeout:3E4,onSuccess:function(k){if(!D.K.isActive()&&GD(D)){D.Z.reset();D.sequenceNumber++;k=k.responseText;var C=kv0(k);if(C){D.player.F1("onHeartbeat",C);var M=C.status==="ok"?C.stop_heartbeat?2:0:C.status==="stop"?1:C.status==="live_stream_offline"?0:-1}else M=(M=k.match(CQL))?M[1]==="0"?0:1:-1;MhL(D,void 0,C,k,M)}},
onError:function(k){GD(D)&&to(D,!0,"net-"+k.status)},
onTimeout:function(){GD(D)&&to(D,!0,"timeout")},
withCredentials:!0})},Xg8=function(D){var O,h;
g.Q(function(V){O=D.player.V();h=D.getVideoData();if(!GD(D))return V.return();if(htx(D))return cbJ(D,O,h),V.v3(0);B7e(D);return g.t(V,S9e(D,O,h),0)})},cbJ=function(D,O,h){var V;
if((V=D.heartbeatParams)!=null&&V.url){var k=g.lF(D.heartbeatParams.url,{request_id:g.vje()});h.jT&&(k=g.lF(k,{vvt:h.jT}),h.mdxEnvironment&&(k=g.lF(k,{mdx_environment:h.mdxEnvironment})));g.OK(O,h.oauthToken).then(function(C){C&&(k=g.lF(k,{access_token:C}));bwL(D,h,k)})}},GD=function(D){var O=D.getVideoData();
return D.player.getPresentingPlayerType()===3||g.l(D.player.getPlayerStateObject(D.getPlayerType()),4)?!1:VhR(D)||O.isLivePlayback?!0:(vv(D),!1)},S9e=function(D,O,h){var V,k,C,M,c,S,Y,J,q,u,H,m,R,f,E,A,v,W,z,X;
return g.Q(function(Z){if(Z.D==1)return V="player/heartbeat",C={videoId:h.videoId,sequenceNumber:D.sequenceNumber,heartbeatServerData:(k=D.jT)!=null?k:h.heartbeatServerData},D.U=D.attestationResponse,h.jy?g.t(Z,D.U,3):Z.v3(2);Z.D!=2&&(C.attestationResponse=Z.K);M=g.PR(h);S=(c=M.client)!=null?c:{};S.utcOffsetMinutes=D.utcOffsetMinutes;C.context=M;C.cpn=h.clientPlaybackNonce;if(Y=typeof Intl!=="undefined"?(new Intl.DateTimeFormat).resolvedOptions().timeZone:null)S.timeZone=Y;J={heartbeatChecks:[]};
if(q=h.getPlayerResponse())h.heartbeatToken&&(C.heartbeatToken=h.heartbeatToken),(u=q.playabilityStatus)&&(H=u.liveStreamability)&&H.liveStreamabilityRenderer&&J.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_LIVE_STREAM_STATUS");h.heartbeatToken&&J.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_YPC");g.tI(O)&&(J.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_UNPLUGGED"),m=Y9v(D),R={},m!==null&&(R.clientPlayerPositionUtcMillis=m),E=(f=D.player.Ev())==null?void 0:g.B7(f),v=((A=E)==null?void 0:A.freePreviewWatchedDuration)||
0,v>0&&(R.freePreviewWatchedDuration={seconds:""+v}),J.unpluggedParams=R);C.heartbeatRequestParams=J;h.isLivePlayback?(W=Y9v(D),W!==null&&(C.playbackState||(C.playbackState={}),C.playbackState.playbackPosition={utcTimeMillis:W})):O.S("enable_heartbeat_vod_playback_position")&&(z=Jb_(D),z!==null&&(C.playbackState||(C.playbackState={}),C.playbackState.playbackPosition={streamTimeMillis:z}));D.player.publish("heartbeatRequest",C);X={timeout:3E4,onSuccess:function(hd){if(!D.K.isActive()&&GD(D)){var Yw=
D.getVideoData(),B=Yw.jy&&D.U==null,r;Yw.jy=!((r=hd.heartbeatAttestationConfig)==null||!r.requiresAttestation)||B;B=hd.playabilityStatus;r=JSON.stringify(B)||"{}";hd.authenticationMismatch&&D.player.KF("authshear",{});var I=-1;var L=hd.playabilityStatus;L&&(D.player.F1("onHeartbeat",L),L.status==="OK"?I=hd.stopHeartbeat?2:0:L.status==="UNPLAYABLE"?I=1:L.status==="LIVE_STREAM_OFFLINE"&&(I=0));D.sequenceNumber&&I===-1||D.Z.reset();D.sequenceNumber++;hd.heartbeatServerData&&(D.jT=hd.heartbeatServerData);
Yw.Ca=hd;(L=hd.playerCueRangeSet)&&g.om(Yw,L);hd.playerCueRanges&&hd.playerCueRanges.length>0&&(Yw.cueRanges=hd.playerCueRanges);var p,Id;((p=hd.progressBarConfig)==null?0:p.progressBarStartPosition)&&((Id=hd.progressBarConfig)==null?0:Id.progressBarEndPosition)&&(Yw.progressBarStartPosition=hd.progressBarConfig.progressBarStartPosition,Yw.progressBarEndPosition=hd.progressBarConfig.progressBarEndPosition);Yw.compositeLiveIngestionOffsetToken=hd.compositeLiveIngestionOffsetToken;hd.compositeLiveStatusToken!==
Yw.compositeLiveStatusToken&&(Yw.compositeLiveStatusToken=hd.compositeLiveStatusToken);Yw.publish("dataupdated");MhL(D,hd,B,r,I)}},
onError:function(hd){GD(D)&&to(D,!0,"net-"+hd.status)},
onTimeout:function(){GD(D)&&to(D,!0,"timeout")}};
g.OK(O,g.bA(h)).then(function(hd){hd&&(X.jE="Bearer "+hd);g.J8(D.Ew,V,C,X)});
g.LT(Z)})},MhL=function(D,O,h,V,k){k===-1?(h="decode "+g.P6(V,3),to(D,!1,h)):k===2?(vv(D),D.J=!0):(D.T=0,D.K.stop(),k===1?(D.J=!1,h&&h.errorCode==="PLAYABILITY_ERROR_CODE_EMBARGOED"&&D.player.NC(!0),k="pe."+(h==null?void 0:h.errorCode)+";ps."+(h==null?void 0:h.status),D.player.kG("heartbeat.stop",2,D.j4(V),k),g.mg("heartbeatActionPlayerHalted",q9m(h)),(O==null?0:O.videoTransitionEndpoint)&&h&&(O=O.videoTransitionEndpoint,(V=g.y(O,g.kG))&&ulL(D,V,h,{itct:O==null?void 0:O.clickTrackingParams}))):(D.J=
!0,V=0,D.W&&h&&(V=x4c(D,O,h),D.player.publish("livestatedata",h)),V?Ao(D,V):Ao(D)))},x4c=function(D,O,h){var V=h.liveStreamability&&h.liveStreamability.liveStreamabilityRenderer,k=!(!V||!(V.switchStreamsImmediately||V.transitionTiming&&V.transitionTiming==="STREAM_TRANSITION_TIMING_IMMEDIATELY"));
O=Hwe(D,O,V);var C=D.getVideoData(),M=D.player.getPlayerStateObject(D.getPlayerType()),c=M.isPlaying()&&!g.Um(C)&&!D.player.isAtLiveHead(D.getPlayerType());if(C.V().x5()){var S,Y=((S=D.player.Sg())==null?void 0:S.BQ())||{};Y.status=h.status||"";Y.dvr=""+ +c;Y["switch"]=""+ +k;Y.ended=""+ +!(!V||!V.displayEndscreen);D.player.KF("heartbeat",Y)}if(c&&!k)return O;k=V&&V.streamTransitionEndpoint&&g.y(V.streamTransitionEndpoint,g.kG);if((V&&V.transitionTiming)==="STREAM_TRANSITION_TIMING_AT_STREAM_END")D.getVideoData().transitionEndpointAtEndOfStream=
k;else if(k&&ulL(D,k,h))return O;if(h.status.toUpperCase()==="OK"){k=V&&V.broadcastId;S=D.D&&D.D.liveStreamability&&D.D.liveStreamability.liveStreamabilityRenderer&&D.D.liveStreamability.liveStreamabilityRenderer.broadcastId;c=k!==S&&k!=null;if(!g.KO(C)||c){var J={video_id:C.videoId};C.OI&&(J.is_live_destination="1");D.player.S("web_player_heartbeat_request_watch_next")||(J.disable_watch_next=!0,J.raw_watch_next_response=C.getWatchNextResponse());J.autonav_state=C.autonavState;J.oauth_token=C.oauthToken;
J.force_gvi=C.jG;J.ag=C.ag;C.Z&&(J.vss_credentials_token=C.Z,J.vss_credentials_token_type=C.BS);C.jT&&(J.vvt=C.jT);V=void 0;g.KO(C)?c&&(V=new Ur("broadcastIdChanged",S+","+k),D.rg("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_BROADCAST_ID_CHANGED",h)):(k&&(V=new Ur("formatsReceived",""+k)),D.rg("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_LIVE_STREAM_WENT_ONLINE",h));D.player.loadVideoByPlayerVars(J,void 0,void 0,void 0,V);return O}D.player.qg("heartbeat",
D.getPlayerType())}V&&V.displayEndscreen&&(D.offlineSlate?(D=D.offlineSlate,D.L=!0,D.WQ&&D.api.qq()):M.isBuffering()&&(C=((J=D.player.Sg())==null?void 0:J.BQ())||{},D.player.KF("hbse",C,!0),D.player.qq(),D.player.F1("onLiveMediaEnded",h)));return O},Hwe=function(D,O,h){return D.player.S("web_player_use_heartbeat_poll_delay_ms")&&(D=Number(O==null?void 0:O.pollDelayMs))?D:(h=Number(h==null?void 0:h.pollDelayMs))?h:0},to=function(D,O,h){var V=D.player.V();
if(!D.K.isActive()){D.K.stop();D.T++;var k=O?"heartbeat.net":"heartbeat.servererror";var C=D.getVideoData();if(C.iG||O&&!g.g$(D.getVideoData())&&!VhR(D)&&C.isLivePlayback)C=!1;else{var M,c;((c=D.heartbeatParams)==null?0:c.retries)?M=D.heartbeatParams.retries:M=C.TJ||5;C=D.T>=M}C?(g.mg("heartbeatActionPlayerHalted",O?{enforcedPolicyToHaltOnNetworkFailure:!0}:q9m()),(O=D.getVideoData())&&O.isLivePlayback?D.player.kG(k,1,"Video playback interrupted. Please try again.",h):D.player.kG(k,1,"Sorry, there was an error licensing this video.",
h)):(V.S("html5_report_non_fatal_heartbeat_error")&&D.player.xx(k,{msg:h}),Ao(D,D.Z.getValue()),g.sL(D.Z))}},q9m=function(D){var O={enforcedPolicyToHaltOnNetworkFailure:!1};
D&&(O.serializedServerContext=D.additionalLoggingData);return O},vv=function(D){D.T=0;
D.K.stop();D.J=!1;D.sequenceNumber=0},l4c=function(D){var O=D.getVideoData(),h=D.player.V();
if(O.isLivePlayback)if(g.D$(h.J)){D.W=!0;D.L=!0;if(!g.QO(h)||g.tI(h))D.offlineSlate=new o0x(D.player),g.F(D,D.offlineSlate),g.X7(D.player,D.offlineSlate.element,4);(O=O.getPlayerResponse())&&O.playabilityStatus&&(D.D=O.playabilityStatus);var V;((V=D.D)==null?void 0:V.status)!=="UNPLAYABLE"&&(D.D?(V=Hwe(D,void 0,D.D.liveStreamability&&D.D.liveStreamability.liveStreamabilityRenderer))?Ao(D,V):Ao(D,7500):Ao(D,1E3))}else D.player.kG("html5.unsupportedlive",2,"HTML5_NO_AVAILABLE_FORMATS_FALLBACK","nolive.1");
else g.BJ(O.qE,"heartbeat")&&D.player.qg("heartbeat",D.getPlayerType())},ulL=function(D,O,h,V){var k=O&&O.videoId;
return k?(D.player.g5(k,Object.assign({},{autonav:"1"},V||{}),void 0,!0,!0,O,g.bA(D.getVideoData())),D.rg("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT",h),!0):!1},Y9v=function(D){return(D=D.player.getProgressState(D.getPlayerType()).ingestionTime)&&isFinite(D)?""+Math.floor(D*1E3):null},Jb_=function(D){return(D=D.player.getCurrentTime(D.getPlayerType()))&&isFinite(D)?""+Math.floor(D*1E3):null},kv0=function(D){try{var O=JSON.parse(D);
return O!=null?O:void 0}catch(h){}},m8R={ERAS:["BC",
"AD"],ERANAMES:["Before Christ","Anno Domini"],NARROWMONTHS:"JFMAMJJASOND".split(""),STANDALONENARROWMONTHS:"JFMAMJJASOND".split(""),MONTHS:"January February March April May June July August September October November December".split(" "),STANDALONEMONTHS:"January February March April May June July August September October November December".split(" "),SHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),STANDALONESHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),
WEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),STANDALONEWEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),SHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),STANDALONESHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),NARROWWEEKDAYS:"SMTWTFS".split(""),STANDALONENARROWWEEKDAYS:"SMTWTFS".split(""),SHORTQUARTERS:["Q1","Q2","Q3","Q4"],QUARTERS:["1st quarter","2nd quarter","3rd quarter","4th quarter"],AMPMS:["AM","PM"],DATEFORMATS:["EEEE, MMMM d, y",
"MMMM d, y","MMM d, y","M/d/yy"],TIMEFORMATS:["h:mm:ss\u202fa zzzz","h:mm:ss\u202fa z","h:mm:ss\u202fa","h:mm\u202fa"],DATETIMEFORMATS:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],FIRSTDAYOFWEEK:6,WEEKENDRANGE:[5,6],FIRSTWEEKCUTOFFDAY:5},etC=m8R;etC=m8R;
var OwU=["ATTESTATION_ERROR_UNKNOWN","ATTESTATION_ERROR_VM_NOT_INITIALIZED","ATTESTATION_ERROR_VM_NO_RESPONSE","ATTESTATION_ERROR_VM_TIMEOUT","ATTESTATION_ERROR_VM_INTERNAL_ERROR"],L0x={300:"STREAMING_DEVICES_QUOTA_PER_24H_EXCEEDED",301:"ALREADY_PINNED_ON_A_DEVICE",303:"STOPPED_BY_ANOTHER_PLAYBACK",304:"TOO_MANY_STREAMS_PER_USER",305:"TOO_MANY_STREAMS_PER_ENTITLEMENT",400:"VIDEO_NOT_FOUND",401:"GEO_FAILURE",402:"STREAMING_NOT_ALLOWED",403:"UNSUPPORTED_DEVICE",405:"VIDEO_FORBIDDEN",500:"PURCHASE_NOT_FOUND",
501:"RENTAL_EXPIRED",502:"PURCHASE_REFUNDED",5E3:"BAD_REQUEST",5001:"CGI_PARAMS_MISSING",5002:"CGI_PARAMS_MALFORMED",5100:"AUTHENTICATION_MISSING",5101:"AUTHENTICATION_MALFORMED",5102:"AUTHENTICATION_EXPIRED",5200:"CAST_TOKEN_MALFORMED",5201:"CAST_TOKEN_EXPIRED",5202:"CAST_TOKEN_FAILED",5203:"CAST_SESSION_VIDEO_MISMATCHED",5204:"CAST_SESSION_DEVICE_MISMATCHED",6E3:"INVALID_DRM_MESSAGE",7E3:"SERVER_ERROR",8E3:"RETRYABLE_ERROR"};g.b=d48.prototype;g.b.zy=etC.FIRSTDAYOFWEEK;g.b.XQ=etC.FIRSTWEEKCUTOFFDAY;
g.b.clone=function(){var D=new d48(this.date);D.zy=this.zy;D.XQ=this.XQ;return D};
g.b.getFullYear=function(){return this.date.getFullYear()};
g.b.getYear=function(){return this.getFullYear()};
g.b.getMonth=function(){return this.date.getMonth()};
g.b.getDate=function(){return this.date.getDate()};
g.b.getTime=function(){return this.date.getTime()};
g.b.getDay=function(){return this.date.getDay()};
g.b.getUTCFullYear=function(){return this.date.getUTCFullYear()};
g.b.getUTCMonth=function(){return this.date.getUTCMonth()};
g.b.getUTCDate=function(){return this.date.getUTCDate()};
g.b.getUTCDay=function(){return this.date.getDay()};
g.b.getUTCHours=function(){return this.date.getUTCHours()};
g.b.getUTCMinutes=function(){return this.date.getUTCMinutes()};
g.b.getTimezoneOffset=function(){return this.date.getTimezoneOffset()};
g.b.set=function(D){this.date=new Date(D.getFullYear(),D.getMonth(),D.getDate())};
g.b.setFullYear=function(D){this.date.setFullYear(D)};
g.b.setYear=function(D){this.setFullYear(D)};
g.b.setMonth=function(D){this.date.setMonth(D)};
g.b.setDate=function(D){this.date.setDate(D)};
g.b.setTime=function(D){this.date.setTime(D)};
g.b.setUTCFullYear=function(D){this.date.setUTCFullYear(D)};
g.b.setUTCMonth=function(D){this.date.setUTCMonth(D)};
g.b.setUTCDate=function(D){this.date.setUTCDate(D)};
g.b.add=function(D){if(D.years||D.months){var O=this.getMonth()+D.months+D.years*12,h=this.getYear()+Math.floor(O/12);O%=12;O<0&&(O+=12);a:{switch(O){case 1:var V=h%4!=0||h%100==0&&h%400!=0?28:29;break a;case 5:case 8:case 10:case 3:V=30;break a}V=31}V=Math.min(V,this.getDate());this.setDate(1);this.setFullYear(h);this.setMonth(O);this.setDate(V)}D.days&&(h=this.getYear(),O=h>=0&&h<=99?-1900:0,D=new Date((new Date(h,this.getMonth(),this.getDate(),12)).getTime()+D.days*864E5),this.setDate(1),this.setFullYear(D.getFullYear()+
O),this.setMonth(D.getMonth()),this.setDate(D.getDate()),fC(this,D.getDate()))};
g.b.C2=function(D){return!(!D||this.getYear()!=D.getYear()||this.getMonth()!=D.getMonth()||this.getDate()!=D.getDate())};
g.b.toString=function(){var D=this.getFullYear(),O=D<0?"-":D>=1E4?"+":"";return[O+wg0(Math.abs(D),O?6:4),wg0(this.getMonth()+1,2),wg0(this.getDate(),2)].join("")+""};
g.b.valueOf=function(){return this.date.valueOf()};var PQU=new g.Qv("addUpcomingEventReminderEndpoint");var gZU=new g.Qv("removeUpcomingEventReminderEndpoint");var Rt8=new g.Qv("updateUpcomingEventReminderButtonStateCommand");var n0_=new g.Qv("upcomingEventReminderButtonRenderer"),N7v=new g.Qv("upcomingEventReminderButtonStateRenderer");g.e(KC,g.DK);
KC.prototype.updateMenuItems=function(){var D=this,O=z_R(this),h=0;h=0;for(var V={};h<O.length;V={Gm:void 0},h++){var k=this.j[h];k||(k=new g.N({X:"div",Y:"ytp-reminder-menu-item",B:{role:"menuitem",tabindex:"0"},N:[{X:"div",Y:"ytp-reminder-menu-item-icon",W3:"{{icon}}"},{X:"div",Y:"ytp-reminder-menu-item-label",W3:"{{text}}"}]}),V.Gm=h,k.listen("click",function(M){return function(){var c=M.Gm;D.ZT();c=z_R(D)[c];D.publish("reminderMenuItemClicked",c.serviceEndpoint||c.command)}}(V)),k.CF(this.items),
this.j[h]=k);
var C=O[h];V=null;switch(C.icon&&C.icon.iconType){case "NOTIFICATIONS":V=s5R();break;case "NOTIFICATIONS_NONE":V=Wp_();break;case "NOTIFICATIONS_ACTIVE":V=g.tA()}C=C.text?g.ag(C.text):"";k.update({icon:V,text:C})}for(;h<this.j.length;)this.j.pop().dispose();h===0?this.ZT():this.kZ(this.D)};
KC.prototype.hide=function(){this.D&&this.D.removeAttribute("aria-haspopup");g.DK.prototype.hide.call(this)};
KC.prototype.show=function(){this.D&&this.D.setAttribute("aria-haspopup","true");g.DK.prototype.show.call(this)};
KC.prototype.fF=function(){g.YC(this.j);g.DK.prototype.fF.call(this)};g.e(Er,g.N);
Er.prototype.L=function(){if(this.toggleButtonRenderer){var D=this.toggleButtonRenderer;D.isToggled?this.j(D.toggledServiceEndpoint):this.j(D.defaultServiceEndpoint);D.isToggled=!D.isToggled;js(this)}else if(this.upcomingEventReminderButtonRenderer)if(this.D&&this.D.WQ)this.D.ZT();else{var O=iHx(this);O&&this.j(O.serviceEndpoint||O.command);O=((D=g.y(O==null?void 0:O.command,g.fP))==null?void 0:D.commands)||[];a:{D=g.P(O);for(var h=D.next();!h.done;h=D.next()){var V=O=void 0;if(h=(O=g.y(h.value,g.TUR))==
null?void 0:(V=O.popup)==null?void 0:V.menuPopupRenderer){D=h;break a}}D=void 0}this.D||(this.D=new KC(this.C,this.J),this.D.CF(this.element),g.F(this,this.D),this.D.subscribe("reminderMenuItemClicked",this.j,this));O=this.D;O.menuPopupRenderer=D;O.updateMenuItems()}};
Er.prototype.j=function(D){var O=g.y(D,PQU),h=g.y(D,gZU);if(D&&(O||h)){if(O){var V=O;var k="notification/add_upcoming_event_reminder"}else h&&(V=h,k="notification/remove_upcoming_event_reminder");if(k&&V&&V.params)for(pgL(this,k,V.params),D=g.P(V.commands||[]),O=D.next();!O.done;O=D.next())if((O=O.value)&&g.y(O,Rt8)){this.K=g.y(O,Rt8).state;js(this);break}}};g.e(o0x,g.N);g.b=o0x.prototype;g.b.getPlayerType=function(){if(this.api.getPresentingPlayerType()===8)return 1};
g.b.getVideoData=function(){return this.api.getVideoData(this.getPlayerType())};
g.b.x7=function(D){var O,h,V=D==null?void 0:(O=D.liveStreamability)==null?void 0:(h=O.liveStreamabilityRenderer)==null?void 0:h.offlineSlate;if(V){this.K=D;O=V.liveStreamOfflineSlateRenderer;O.canShowCountdown?this.US():ZHe(this,O);var k,C,M,c;if(h=D==null?void 0:(k=D.liveStreamability)==null?void 0:(C=k.liveStreamabilityRenderer)==null?void 0:(M=C.offlineSlate)==null?void 0:(c=M.liveStreamOfflineSlateRenderer)==null?void 0:c.thumbnail){k=0;C=null;M=h.thumbnails;for(c=0;c<M.length;c++)M[c].width>
k&&(k=M[c].width||0,C=M[c].url);C&&(this.background.style.backgroundImage="url("+C+")")}else this.background.style.backgroundImage="";O.actionButtons||O.reminderButton?(this.D||(this.D=new Er(this.api),this.D.CF(this.z2("ytp-offline-slate-buttons")),g.F(this,this.D)),Fp8(this.D,O.actionButtons&&O.actionButtons[0],O.reminderButton)):this.D&&Fp8(this.D,null,null);this.K=D}else this.K=null;this.t3()};
g.b.t3=function(D){if(this.api.getPresentingPlayerType()===8)var O=!0;else{var h=this.api.getPlayerStateObject(),V=this.getVideoData();O=V.isLivePlayback&&(h.isBuffering()||g.l(h,2)||g.l(h,64));var k=V.autonavState===2&&g.l(h,2);h=h.isPlaying()&&!g.Um(V)&&!this.api.isAtLiveHead(void 0,!0);O=O&&!h&&!k}O&&this.K?this.WQ?(D==null?0:g.Rs(D,2))&&!this.getVideoData().Ig&&(g.uY(this.element,"ytp-offline-slate-collapsed"),this.W.stop(),g.uY(this.j,"ytp-offline-slate-bar-fade"),this.J.start()):(this.show(),
this.W.start(),this.api.publish("offlineslatestatechange"),this.L&&this.api.qq()):this.WQ&&(this.hide(),this.api.publish("offlineslatestatechange"))};
g.b.US=function(){var D,O,h,V,k=(D=this.K)==null?void 0:(O=D.liveStreamability)==null?void 0:(h=O.liveStreamabilityRenderer)==null?void 0:(V=h.offlineSlate)==null?void 0:V.liveStreamOfflineSlateRenderer;k&&(D=Math.floor(g.xw()/1E3),O=k.canShowCountdown&&Number(k.scheduledStartTime),!O||O<=D?(ZHe(this,k),this.countdownTimer.stop()):(ZHe(this,k,g.t5(O-D)),g.kF(this.countdownTimer)))};
g.b.fF=function(){this.countdownTimer.dispose();this.countdownTimer=null;g.N.prototype.fF.call(this)};Ur.prototype.K=function(D){return this.trigger&&D.trigger?this.module===D.module&&this.trigger===D.trigger&&this.D===D.D:!1};
Ur.prototype.isExpired=function(){return(0,g.sk)()-this.j>6E4};
Ur.prototype.toString=function(){return this.module+":"+this.trigger+":"+this.D};g.e(I4v,g.dX);g.b=I4v.prototype;g.b.fF=function(){vv(this);this.player.aH("heartbeat");g.dX.prototype.fF.call(this)};
g.b.onCueRangeEnter=function(){this.L=!0;Ao(this,2E3)};
g.b.FE=function(D){this.heartbeatParams=D;Ao(this,2E3)};
g.b.sO=function(D){var O;this.player.getPresentingPlayerType()!==8&&((O=this.D)==null?void 0:O.status)!=="UNPLAYABLE"&&(g.l(D.state,2)||g.l(D.state,64)?(vv(this),this.W&&(this.L=!0,Ao(this,1E3))):(g.l(D.state,1)||g.l(D.state,8))&&Ao(this,2E3))};
g.b.gM=function(){this.player.getPresentingPlayerType()!==3&&Ao(this,2E3)};
g.b.getPlayerType=function(){if(this.player.getPresentingPlayerType()===8)return 1};
g.b.getVideoData=function(){return this.player.getVideoData(this.getPlayerType())};
g.b.PS=function(D){switch(D){case 4:case 3:return!1}return!0};
g.b.rg=function(D,O,h){D={trigger:D,reason:O};h&&(D.serializedServerContext=h.additionalLoggingData);g.mg("heartbeatActionPlayerTransitioned",D)};
g.b.j4=function(D){var O="LICENSE",h=kv0(D);if(h)return h.reason||g.CX[O]||"";if(D=D.match(CQL))if(D=Number(D[1]))O=(O=L0x[D.toString()])?O:"LICENSE";return g.CX[O]||""};
g.b.tb=function(){return!!this.offlineSlate&&this.offlineSlate.WQ};
var CQL=/^GLS\/1.0 (\d+) (\w+).*?\r\n\r\n([\S\s]*)$/;g.TP("heartbeat",I4v);})(_yt_player);
